### ISSUE TITLE
unable to locate the data and scripts

### ISSUE THREAD

**Issue by YimRegister** [SAILResearch/replication-stackoverflow_topics_trends#2]
I'm experiencing the same issue; where can we locate the entire replication package? including the data and scripts? Thank you.

**Comment by golivax** [comment]
Hi. I double-checked with Ahmed and we had a disk failure. Therefore, unfortunately, these files are not available anymore. Having said that, the data should be easy to get using Stackoverflow dumps. Check here https://data.stackexchange.com/ and https://archive.org/details/stackexchange. Thanks!
